/**
 * Permission + role identifiers. These MUST stay in sync with the backend enums
 * np.com.lims.rbac.entity.PermissionName / RoleName. The backend is authoritative;
 * these are used only to shape the UI (hide actions the user cannot perform).
 */
export const PERMISSIONS = {
  PATIENT_READ: 'PATIENT_READ',
  PATIENT_WRITE: 'PATIENT_WRITE',
  PATIENT_CONFIDENTIAL: 'PATIENT_CONFIDENTIAL',
  PATIENT_MERGE: 'PATIENT_MERGE',
  DOCTOR_READ: 'DOCTOR_READ',
  DOCTOR_WRITE: 'DOCTOR_WRITE',
  DEPARTMENT_READ: 'DEPARTMENT_READ',
  DEPARTMENT_WRITE: 'DEPARTMENT_WRITE',
  TEST_CATALOG_READ: 'TEST_CATALOG_READ',
  TEST_CATALOG_WRITE: 'TEST_CATALOG_WRITE',
  LAB_ORDER_READ: 'LAB_ORDER_READ',
  LAB_ORDER_WRITE: 'LAB_ORDER_WRITE',
  SAMPLE_READ: 'SAMPLE_READ',
  SAMPLE_COLLECT: 'SAMPLE_COLLECT',
  SAMPLE_RECEIVE: 'SAMPLE_RECEIVE',
  SAMPLE_REJECT: 'SAMPLE_REJECT',
  RESULT_READ: 'RESULT_READ',
  RESULT_ENTER: 'RESULT_ENTER',
  RESULT_VERIFY: 'RESULT_VERIFY',
  RESULT_APPROVE: 'RESULT_APPROVE',
  RESULT_AMEND: 'RESULT_AMEND',
  REPORT_READ: 'REPORT_READ',
  REPORT_GENERATE: 'REPORT_GENERATE',
  REPORT_DELIVER: 'REPORT_DELIVER',
  INVOICE_READ: 'INVOICE_READ',
  INVOICE_WRITE: 'INVOICE_WRITE',
  INVOICE_CANCEL: 'INVOICE_CANCEL',
  PAYMENT_READ: 'PAYMENT_READ',
  PAYMENT_WRITE: 'PAYMENT_WRITE',
  REFUND_REQUEST: 'REFUND_REQUEST',
  REFUND_APPROVE: 'REFUND_APPROVE',
  IRD_SUBMISSION_READ: 'IRD_SUBMISSION_READ',
  IRD_SUBMISSION_MANAGE: 'IRD_SUBMISSION_MANAGE',
  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_WRITE: 'INVENTORY_WRITE',
  REPORTING_READ: 'REPORTING_READ',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  AUDIT_READ: 'AUDIT_READ',
  USER_READ: 'USER_READ',
  USER_WRITE: 'USER_WRITE',
  ROLE_READ: 'ROLE_READ',
  SETTINGS_READ: 'SETTINGS_READ',
  SETTINGS_WRITE: 'SETTINGS_WRITE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  LAB_ADMINISTRATOR: 'LAB_ADMINISTRATOR',
  RECEPTIONIST: 'RECEPTIONIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  PATHOLOGIST: 'PATHOLOGIST',
  ACCOUNTANT: 'ACCOUNTANT',
  DOCTOR: 'DOCTOR',
  SAMPLE_COLLECTION_STAFF: 'SAMPLE_COLLECTION_STAFF',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];
